package com.example.learning_management_system_api.utils.enums;

public enum NotificationTopic {
  COURSE_STATUS_CHANGED,
  LESSON_CREATED,
  LESSON_UPDATED,
  QUIZ_PUBLISHED,
  STUDY_REMINDER,
  COURSE_COMPLETED,
  REFUND_STATUS_CHANGED,

  INSTRUCTOR_COURSE_APPROVED,
  INSTRUCTOR_COURSE_REJECTED,
  COURSE_PUBLISHED_TOGGLE,
  CONTENT_REMOVED,
  NEW_REVIEW,
  ORDER_CREATED,
  REVENUE_DAILY_SUMMARY,

  // Admin
  ADMIN_NEW_INSTRUCTOR_PENDING,
  ADMIN_COURSE_SUBMITTED,
  ADMIN_CONTENT_REPORTED,

  // Student
  ASSIGNMENT_GRADED,
  ASSIGNMENT_CREATED, // ✅ NEW: instructor tạo assignment -> notify student

  // Instructor
  STUDENT_ENROLLED,
  ASSIGNMENT_SUBMITTED
}
